# Generated by Django 5.2.17 on 2026-09-12 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_ticketactivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketactivity",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="tickets.ticket",
            ),
        ),
    ]
